package lecho.sample.green_dao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import lecho.sample.green_dao.dao.Faculty;
import lecho.sample.green_dao.dao.Category;
import lecho.sample.green_dao.dao.Place;

import lecho.sample.green_dao.dao.FacultyDao;
import lecho.sample.green_dao.dao.CategoryDao;
import lecho.sample.green_dao.dao.PlaceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig facultyDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig placeDaoConfig;

    private final FacultyDao facultyDao;
    private final CategoryDao categoryDao;
    private final PlaceDao placeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        facultyDaoConfig = daoConfigMap.get(FacultyDao.class).clone();
        facultyDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        facultyDao = new FacultyDao(facultyDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        placeDao = new PlaceDao(placeDaoConfig, this);

        registerDao(Faculty.class, facultyDao);
        registerDao(Category.class, categoryDao);
        registerDao(Place.class, placeDao);
    }
    
    public void clear() {
        facultyDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        placeDaoConfig.getIdentityScope().clear();
    }

    public FacultyDao getFacultyDao() {
        return facultyDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

}
