package lecho.sample.green_dao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FACULTY.
 */
public class Faculty {

    private Long id;
    private String name;
    private String description;
    private Long placeId;

    public Faculty() {
    }

    public Faculty(Long id) {
        this.id = id;
    }

    public Faculty(Long id, String name, String description, Long placeId) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.placeId = placeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getPlaceId() {
        return placeId;
    }

    public void setPlaceId(Long placeId) {
        this.placeId = placeId;
    }

}
